services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks: [snapdocs_net]

  auth:
    build: ./backend/auth
    env_file:
      - ./backend/auth/.env
    depends_on:
      - mongo
    ports:
      - "4500:4500"
    networks: [snapdocs_net]

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    networks: [snapdocs_net]

  frontend:
    build: ./frontend
    depends_on:
      - backend
      - auth
    ports:
      - "8080:80"
    networks: [snapdocs_net]
