version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: snapuser
      POSTGRES_PASSWORD: snappass
      POSTGRES_DB: snapdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./auth-service/.env
    ports:
      - "8000:8000"
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
